# Generated by Django 5.1.1 on 2024-09-28 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Enter the question text.')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the question is active.')),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(help_text="Store user's answer.")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when the answer was recorded.')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='portfolios.chatquestion')),
            ],
        ),
    ]
