# Generated by Django 5.1.1 on 2024-09-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='question',
        ),
        migrations.DeleteModel(
            name='ChatQuestion',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
    ]
