# Generated by Django 5.0.3 on 2024-10-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0009_userinfo_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='selected_background',
            field=models.CharField(choices=[('bg1', 'Background 1'), ('bg2', 'Background 2'), ('bg3', 'Background 3'), ('bg4', 'Background 4')], default='bg1', max_length=3),
        ),
    ]
