# Generated by Django 5.0.3 on 2024-11-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0010_userinfo_selected_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='selected_background',
            field=models.CharField(choices=[('bg1', 'Background 1'), ('bg2', 'Background 2'), ('bg3', 'Background 3'), ('bg4', 'Background 4'), ('bg5', 'Background 5'), ('bg6', 'Background 6'), ('bg7', 'Background 7'), ('bg8', 'Background 8')], default='bg1', max_length=3),
        ),
    ]
