# Generated by Django 5.0.3 on 2024-11-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0011_alter_userinfo_selected_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='userUrl',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
