# Generated by Django 5.0.3 on 2024-11-07 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0015_sectiondata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='highlight_thumbnail_image',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='highlight_title',
        ),
    ]
