# Generated by Django 5.1.1 on 2024-11-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0023_alter_userinfo_selected_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiondata',
            name='desc',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sectiondata',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
