# Generated by Django 5.1.1 on 2025-04-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0024_alter_sectiondata_desc_alter_sectiondata_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alldesigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_file', models.FileField(max_length=255, upload_to='templates/')),
                ('location', models.CharField(choices=[('designs', 'Designs Folder'), ('animated', 'Animated Folder')], default='designs', max_length=10)),
                ('code_name', models.CharField(max_length=6, unique=True)),
            ],
        ),
    ]
