# Generated by Django 5.1.1 on 2025-04-08 14:15

import portfolios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0025_alldesigns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alldesigns',
            name='template_file',
            field=models.FileField(max_length=255, upload_to=portfolios.models.custom_upload_path),
        ),
    ]
